### ISSUE TITLE
distributed values

### ISSUE THREAD

**Issue by mla** [ap/XML-Builder#2]
Not sure how to phrase it, but is there a way to distribute a tag across a set of other tags as a group, rather than individually?

IOW, say I need this output:

``` xml
<setting>
  <name>a</name>
  <value>foo</value>
</setting>
<setting>
  <name>b</name>
  <value>bar</value>
</setting>
```

I looked at 02-distributivity.t but didn't see an example like that there. I tried something along these lines:

``` perl
$x->foreach([$x->name('a'), $x->value('foo')], [$x->name('b'), $x->value('bar')])
```

but that didn't work. 

And is there somewhere more appropriate to discuss this module?

Thanks.

**Comment by ap** [comment]
That should have worked, and now it will. 0.906 is on its way to CPAN – thanks for your report.

This place is perfectly fine for bug reports. My email would work for help requests; there is no public forum for it.

(The truth is it’s semi-abandoned; I like the core pieces of the API very much, but the implementation is very unsatisfactory and pokes through to the API in too many places. But I’ve never been able to figure out how to implement it differently _and_ better. So it sits in a sort of limbo. However, if you’ve managed to figure it out without docs – I won’t be breaking your code.)

**Comment by mla** [comment]
Thanks! 

Sorry to hear it's semi-abandoned since the interface is really elegant...

**Comment by ap** [comment]
So am I. Well, never-finished really… I never got the guts to a point where I was happy with them. It’s slow and memory hungry for what it does, but I never figured out how to factor the code better without compromising the interface. A huge pity… I wanted this module so badly, and still want it even now. The other XML generators all have painfully clumsy interfaces. Sigh.

I don’t know, I’m still hoping for a bolt of inspiration to strike. There _has_ to be a way to do this well!

NB though, as I said, abandoned does not mean unsupported. (C.f. the progression of this issue.)
